# Grafana
grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - "grafana.158.160.206.224.nip.io"
    path: /
    pathType: Prefix

# Prometheus
prometheus:
  enabled: true
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

# Alertmanager
alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

# Node Exporter
nodeExporter:
  enabled: true

# Kubernetes Service Monitor
kubelet:
  enabled: true

# Уменьшаем ресурсы для диплома
prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
